info: {title: Subscription API, version: 1.0.0}
openapi: 3.0.2
paths:
  /subscriptions:
    post:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                hub.callback: {type: string}
                hub.lease_seconds: {format: int64, type: integer}
                hub.mode: {type: string}
                hub.topic: {type: string}
              required: [hub.topic, hub.callback, hub.mode]
              type: object
      responses:
        '202': {description: Indicates successful subscription}
