info: {title: Document API, version: 1.0.0}
openapi: 3.0.2
paths:
  /jurisdictions/{jurisdiction_name}:
    post:
      parameters:
      - in: path
        name: jurisdiction_name
        required: true
        schema: {type: string}
      requestBody:
        content:
          application/binary:
            schema: {format: binary, type: string}
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  multihash: {format: uuid, type: string}
                type: object
          description: Returns document id
  /{uri}:
    get:
      parameters:
      - in: path
        name: uri
        required: true
        schema: {format: uuid, type: string}
      responses:
        '200':
          content:
            application/binary:
              schema: {format: binary, type: string}
          description: Returns document
