components:
  schemas:
    Message:
      properties:
        channel_id: {type: string}
        channel_txn_id: {type: string}
        obj: {type: string}
        predicate: {type: string}
        receiver: {type: string}
        sender: {type: string}
        sender_ref: {type: string}
        status: {type: string}
        subject: {type: string}
      required: [obj, predicate, receiver, sender, subject]
      type: object
info: {title: Message API, version: 1.0.0}
openapi: 3.0.2
paths:
  /message/{reference}:
    get:
      parameters:
      - in: path
        name: reference
        required: true
        schema: {type: string}
      responses:
        '201':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Message'}
          description: Is this the right code?
    patch:
      parameters:
      - in: path
        name: reference
        required: true
        schema: {type: string}
      requestBody:
        content:
          application/json:
            schema: {$ref: '#/components/schemas/Message'}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Message'}
          description: Update a message
  /message:
    post:
      requestBody:
        content:
          application/binary:
            schema: {$ref: '#/components/schemas/Message'}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Message'}
          description: The message was successfully sent to the node
